Repository gajjartejas/react-native-lan-port-scanner, pull requests merged in 2023-10, with the labels that each got.

#17 Fix startScan function to work with custom IP Ranges
  src/index.ts
  src/internal/types.ts
Labels: enhancement

#18 feat(release): release v1.2.0
  package.json
  src/index.ts
Labels: release

#21 fix(refractor): code refractor
  src/index.ts
Labels: refractor

#22 feat: example updated
  example/App.tsx
  example/package-lock.json
  example/package.json
Labels: example

#23 feat(release): release v1.3.0
  package.json
Labels: release
